# Generated by Django 4.2.25 on 2025-10-30 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=10)),
                ('img', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('course', models.ForeignKey(db_column='course_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='course')),
                ('student', models.ForeignKey(db_column='student_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(null=True, through='student.StudentCourses', to='course.course'),
        ),
    ]
