# Generated by Django 4.2.25 on 2025-10-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(through='student.StudentCourses', to='course.course'),
        ),
        migrations.CreateModel(
            name='StudentMTMCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=10)),
                ('img', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('status', models.BooleanField(default=True)),
                ('courses', models.ManyToManyField(to='course.course')),
            ],
        ),
    ]
